name: GHAction zadanko2

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  ci_step:
    name: Build, tag, test and push Docker image to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4

      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/zadanko2
          flavor: latest=true
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zadanko2:cache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zadanko:cache
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/zadanko2:latest
            ${{ steps.meta.outputs.tags }}

      - name: Scan image for vulnerabilities
        id: vulnerability_scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ vars.DOCKERHUB_USERNAME }}/zadanko2:latest
          only-severities: critical,high
          exit-code: true

      - name: Echo debug info
        run: |
          echo "Pass variable value: ${{ steps.vulnerability_scan.outputs.pass }}"
          echo "Meta tags: ${{ steps.meta.outputs.tags }}"
          echo "Image name: ${{ vars.DOCKERHUB_USERNAME }}/zadanko2:latest"
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.repository: ${{ github.repository }}"

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: radzp
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/radzp/zadanko2:${{ github.sha }}